## Importing the libraries

In [17]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable

## Importing the dataset

In [18]:
movies = pd.read_csv('ml-1m/movies.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
users = pd.read_csv('ml-1m/users.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
ratings = pd.read_csv('ml-1m/ratings.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
display(movies)
display(pd.DataFrame(users))
display(pd.DataFrame(ratings))

         0                                   1                             2
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
...    ...                                 ...                           ...
3878  3948             Meet the Parents (2000)                        Comedy
3879  3949          Requiem for a Dream (2000)                         Drama
3880  3950                    Tigerland (2000)                         Drama
3881  3951             Two Family House (2000)                         Drama
3882  3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 3 columns]

         0  1   2   3      4
0        1  F   1  10  48067
1        2  M  56  16  70072
2        3  M  25  15  55117
3        4  M  45   7  02460
4        5  M  25  20  55455
...    ... ..  ..  ..    ...
6035  6036  F  25  15  32603
6036  6037  F  45   1  76006
6037  6038  F  56   1  14706
6038  6039  F  45   0  01060
6039  6040  M  25   6  11106

[6040 rows x 5 columns]

            0     1  2          3
0           1  1193  5  978300760
1           1   661  3  978302109
2           1   914  3  978301968
3           1  3408  4  978300275
4           1  2355  5  978824291
...       ...   ... ..        ...
1000204  6040  1091  1  956716541
1000205  6040  1094  5  956704887
1000206  6040   562  5  956704746
1000207  6040  1096  4  956715648
1000208  6040  1097  4  956715569

[1000209 rows x 4 columns]

## Preparing the training set and the test set

In [19]:
training_set = pd.read_csv('ml-100k/u1.base', delimiter = '\t')
training_set = np.array(training_set, dtype = 'int')
test_set = pd.read_csv('ml-100k/u1.test', delimiter = '\t')
test_set = np.array(test_set, dtype = 'int')
display(pd.DataFrame(training_set))
display(pd.DataFrame(test_set))

         0     1  2          3
0        1     2  3  876893171
1        1     3  4  878542960
2        1     4  3  876893119
3        1     5  3  889751712
4        1     7  4  875071561
...    ...   ... ..        ...
79994  943  1067  2  875501756
79995  943  1074  4  888640250
79996  943  1188  3  888640250
79997  943  1228  3  888640275
79998  943  1330  3  888692465

[79999 rows x 4 columns]

         0     1  2          3
0        1    10  3  875693118
1        1    12  5  878542960
2        1    14  5  874965706
3        1    17  3  875073198
4        1    20  4  887431883
...    ...   ... ..        ...
19994  458   648  4  886395899
19995  458  1101  4  886397931
19996  459   934  3  879563639
19997  460    10  3  882912371
19998  462   682  5  886365231

[19999 rows x 4 columns]

## Getting the number of users and movies

In [20]:
nb_users = int(max(max(training_set[:,0]), max(test_set[:,0])))
nb_movies = int(max(max(training_set[:,1]), max(test_set[:,1])))
print(nb_users,nb_movies)

943 1682

## Converting the data into an array with users in lines and movies in columns

In [21]:
def convert(data):
    new_data = []
    for id_users in range(1, nb_users + 1):
        id_movies = data[:,1][data[:,0] == id_users]
        id_ratings = data[:,2][data[:,0] == id_users]
        ratings = np.zeros(nb_movies)
        ratings[id_movies - 1] = id_ratings
        new_data.append(list(ratings))
    return new_data
training_set = convert(training_set)
test_set = convert(test_set)
display(pd.DataFrame(training_set))
display(pd.DataFrame(test_set))

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.0,3.0,4.0,3.0,3.0,0.0,4.0,1.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
942,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Converting the data into Torch tensors

In [22]:
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)
display(pd.DataFrame(training_set))
display(pd.DataFrame(test_set))

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,tensor(0.),tensor(3.),tensor(4.),tensor(3.),tensor(3.),tensor(0.),tensor(4.),tensor(1.),tensor(5.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
1,tensor(4.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(2.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
2,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
3,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
4,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(5.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
939,tensor(0.),tensor(0.),tensor(0.),tensor(2.),tensor(0.),tensor(0.),tensor(4.),tensor(5.),tensor(3.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
940,tensor(5.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(4.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
941,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
942,tensor(0.),tensor(5.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(3.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(3.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
1,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
2,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
3,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
4,tensor(4.),tensor(3.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
939,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
940,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
941,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)
942,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),...,tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.),tensor(0.)

## Creating the architecture of the Neural Network

In [23]:
class SAE(nn.Module): # inheritance from nn module to use the parent variables
    def __init__(self,):
        super(SAE,self).__init__() # all inherated classes and methods
        self.fc1=nn.Linear(nb_movies,20)  # the first hidden layers nodes
        self.fc2=nn.Linear(20,10)
        self.fc3=nn.Linear(10,20) # the first decoding part larger output smaller input
        self.fc4=nn.Linear(20,nb_movies)
        self.activation=nn.Sigmoid()
    
    def forward(self,x): # the action of full connections and activation functions
        x=self.activation(self.fc1(x)) # the encoded vector
        x=self.activation(self.fc2(x)) 
        x=self.activation(self.fc3(x)) # decoding
        x=self.fc4(x) # our final output vector
        return x

sae=SAE()
criterion=nn.MSELoss()
optimizer=optim.RMSprop(sae.parameters(),lr=0.01,weight_decay=0.5)

## Training the SAE

In [24]:
nb_epoch=200

for epoch in range(1,nb_epoch+1):
    
    train_loss=0
    s=0. # the number of users who only rated
    
    for id_user in range(nb_users):
        
        input=Variable(training_set[id_user]).unsqueeze(0) # py torch doesn't accept vector of one Dim it takes two dim for patches
        target = input.clone() # copy of our input
        
        if torch.sum(target.data>0) > 0:
           output=sae(input)
           target.require_grad=False # don't compute the gradient with respect to the target
           output[target==0]=0 # the values of the correspinds rating in target is equal to 0 (unrated) so we will make it to 0 so that it's not our computation
           loss=criterion(output,target)
           mean_corrector=nb_movies/float(torch.sum(target.data>0)+1e-10)
           loss.backward()  # it will tell us to increase or decrease the weights
           train_loss+=np.sqrt(loss.data*mean_corrector)
           s+=1
           optimizer.step() # update the weight by how much 
           
    print('epoch: '+str(epoch)+' loss: '+str(train_loss/s))

epoch: 1 loss: tensor(1.7706)
epoch: 2 loss: tensor(1.0966)
epoch: 3 loss: tensor(1.0534)
epoch: 4 loss: tensor(1.0383)
epoch: 5 loss: tensor(1.0309)
epoch: 6 loss: tensor(1.0266)
epoch: 7 loss: tensor(1.0236)
epoch: 8 loss: tensor(1.0220)
epoch: 9 loss: tensor(1.0207)
epoch: 10 loss: tensor(1.0196)
epoch: 11 loss: tensor(1.0187)
epoch: 12 loss: tensor(1.0184)
epoch: 13 loss: tensor(1.0179)
epoch: 14 loss: tensor(1.0175)
epoch: 15 loss: tensor(1.0173)
epoch: 16 loss: tensor(1.0169)
epoch: 17 loss: tensor(1.0167)
epoch: 18 loss: tensor(1.0167)
epoch: 19 loss: tensor(1.0165)
epoch: 20 loss: tensor(1.0160)
epoch: 21 loss: tensor(1.0162)
epoch: 22 loss: tensor(1.0160)
epoch: 23 loss: tensor(1.0158)
epoch: 24 loss: tensor(1.0157)
epoch: 25 loss: tensor(1.0157)
epoch: 26 loss: tensor(1.0156)
epoch: 27 loss: tensor(1.0153)
epoch: 28 loss: tensor(1.0152)
epoch: 29 loss: tensor(1.0129)
epoch: 30 loss: tensor(1.0120)
epoch: 31 loss: tensor(1.0098)
epoch: 32 loss: tensor(1.0098)
epoch: 33 loss: tensor(1.0057)
epoch: 34 loss: tensor(1.0054)
epoch: 35 loss: tensor(1.0017)
epoch: 36 loss: tensor(1.0007)
epoch: 37 loss: tensor(0.9975)
epoch: 38 loss: tensor(0.9987)
epoch: 39 loss: tensor(0.9948)
epoch: 40 loss: tensor(0.9932)
epoch: 41 loss: tensor(0.9930)
epoch: 42 loss: tensor(0.9912)
epoch: 43 loss: tensor(0.9880)
epoch: 44 loss: tensor(0.9890)
epoch: 45 loss: tensor(0.9833)
epoch: 46 loss: tensor(0.9825)
epoch: 47 loss: tensor(0.9789)
epoch: 48 loss: tensor(0.9785)
epoch: 49 loss: tensor(0.9777)
epoch: 50 loss: tensor(0.9801)
epoch: 51 loss: tensor(0.9803)
epoch: 52 loss: tensor(0.9770)
epoch: 53 loss: tensor(0.9788)
epoch: 54 loss: tensor(0.9747)
epoch: 55 loss: tensor(0.9735)
epoch: 56 loss: tensor(0.9744)
epoch: 57 loss: tensor(0.9756)
epoch: 58 loss: tensor(0.9731)
epoch: 59 loss: tensor(0.9734)
epoch: 60 loss: tensor(0.9690)
epoch: 61 loss: tensor(0.9675)
epoch: 62 loss: tensor(0.9668)
epoch: 63 loss: tensor(0.9710)
epoch: 64 loss: tensor(0.9686)
epoch: 65 loss: tensor(0.9659)
epoch: 66 loss: tensor(0.9757)
epoch: 67 loss: tensor(0.9742)
epoch: 68 loss: tensor(0.9699)
epoch: 69 loss: tensor(0.9664)
epoch: 70 loss: tensor(0.9649)
epoch: 71 loss: tensor(0.9664)
epoch: 72 loss: tensor(0.9616)
epoch: 73 loss: tensor(0.9659)
epoch: 74 loss: tensor(0.9638)
epoch: 75 loss: tensor(0.9680)
epoch: 76 loss: tensor(0.9616)
epoch: 77 loss: tensor(0.9651)
epoch: 78 loss: tensor(0.9629)
epoch: 79 loss: tensor(0.9569)
epoch: 80 loss: tensor(0.9555)
epoch: 81 loss: tensor(0.9549)
epoch: 82 loss: tensor(0.9560)
epoch: 83 loss: tensor(0.9591)
epoch: 84 loss: tensor(0.9508)
epoch: 85 loss: tensor(0.9531)
epoch: 86 loss: tensor(0.9582)
epoch: 87 loss: tensor(0.9586)
epoch: 88 loss: tensor(0.9548)
epoch: 89 loss: tensor(0.9596)
epoch: 90 loss: tensor(0.9588)
epoch: 91 loss: tensor(0.9613)
epoch: 92 loss: tensor(0.9579)
epoch: 93 loss: tensor(0.9540)
epoch: 94 loss: tensor(0.9533)
epoch: 95 loss: tensor(0.9548)
epoch: 96 loss: tensor(0.9492)
epoch: 97 loss: tensor(0.9489)
epoch: 98 loss: tensor(0.9489)
epoch: 99 loss: tensor(0.9520)
epoch: 100 loss: tensor(0.9474)
epoch: 101 loss: tensor(0.9486)
epoch: 102 loss: tensor(0.9452)
epoch: 103 loss: tensor(0.9479)
epoch: 104 loss: tensor(0.9438)
epoch: 105 loss: tensor(0.9453)
epoch: 106 loss: tensor(0.9424)
epoch: 107 loss: tensor(0.9435)
epoch: 108 loss: tensor(0.9414)
epoch: 109 loss: tensor(0.9437)
epoch: 110 loss: tensor(0.9418)
epoch: 111 loss: tensor(0.9409)
epoch: 112 loss: tensor(0.9397)
epoch: 113 loss: tensor(0.9421)
epoch: 114 loss: tensor(0.9380)
epoch: 115 loss: tensor(0.9398)
epoch: 116 loss: tensor(0.9370)
epoch: 117 loss: tensor(0.9391)
epoch: 118 loss: tensor(0.9411)
epoch: 119 loss: tensor(0.9413)
epoch: 120 loss: tensor(0.9432)
epoch: 121 loss: tensor(0.9421)
epoch: 122 loss: tensor(0.9404)
epoch: 123 loss: tensor(0.9409)
epoch: 124 loss: tensor(0.9385)
epoch: 125 loss: tensor(0.9382)
epoch: 126 loss: tensor(0.9380)
epoch: 127 loss: tensor(0.9444)
epoch: 128 loss: tensor(0.9399)
epoch: 129 loss: tensor(0.9385)
epoch: 130 loss: tensor(0.9372)
epoch: 131 loss: tensor(0.9362)
epoch: 132 loss: tensor(0.9339)
epoch: 133 loss: tensor(0.9340)
epoch: 134 loss: tensor(0.9337)
epoch: 135 loss: tensor(0.9332)
epoch: 136 loss: tensor(0.9320)
epoch: 137 loss: tensor(0.9328)
epoch: 138 loss: tensor(0.9305)
epoch: 139 loss: tensor(0.9322)
epoch: 140 loss: tensor(0.9303)
epoch: 141 loss: tensor(0.9321)
epoch: 142 loss: tensor(0.9313)
epoch: 143 loss: tensor(0.9292)
epoch: 144 loss: tensor(0.9304)
epoch: 145 loss: tensor(0.9309)
epoch: 146 loss: tensor(0.9293)
epoch: 147 loss: tensor(0.9301)
epoch: 148 loss: tensor(0.9282)
epoch: 149 loss: tensor(0.9342)
epoch: 150 loss: tensor(0.9351)
epoch: 151 loss: tensor(0.9346)
epoch: 152 loss: tensor(0.9328)
epoch: 153 loss: tensor(0.9327)
epoch: 154 loss: tensor(0.9316)
epoch: 155 loss: tensor(0.9320)
epoch: 156 loss: tensor(0.9301)
epoch: 157 loss: tensor(0.9312)
epoch: 158 loss: tensor(0.9300)
epoch: 159 loss: tensor(0.9309)
epoch: 160 loss: tensor(0.9295)
epoch: 161 loss: tensor(0.9299)
epoch: 162 loss: tensor(0.9291)
epoch: 163 loss: tensor(0.9288)
epoch: 164 loss: tensor(0.9281)
epoch: 165 loss: tensor(0.9280)
epoch: 166 loss: tensor(0.9274)
epoch: 167 loss: tensor(0.9276)
epoch: 168 loss: tensor(0.9263)
epoch: 169 loss: tensor(0.9266)
epoch: 170 loss: tensor(0.9260)
epoch: 171 loss: tensor(0.9263)
epoch: 172 loss: tensor(0.9254)
epoch: 173 loss: tensor(0.9256)
epoch: 174 loss: tensor(0.9247)
epoch: 175 loss: tensor(0.9259)
epoch: 176 loss: tensor(0.9243)
epoch: 177 loss: tensor(0.9241)
epoch: 178 loss: tensor(0.9234)
epoch: 179 loss: tensor(0.9241)
epoch: 180 loss: tensor(0.9230)
epoch: 181 loss: tensor(0.9239)
epoch: 182 loss: tensor(0.9239)
epoch: 183 loss: tensor(0.9235)
epoch: 184 loss: tensor(0.9214)
epoch: 185 loss: tensor(0.9212)
epoch: 186 loss: tensor(0.9202)
epoch: 187 loss: tensor(0.9207)
epoch: 188 loss: tensor(0.9200)
epoch: 189 loss: tensor(0.9197)
epoch: 190 loss: tensor(0.9189)
epoch: 191 loss: tensor(0.9191)
epoch: 192 loss: tensor(0.9213)
epoch: 193 loss: tensor(0.9208)
epoch: 194 loss: tensor(0.9180)
epoch: 195 loss: tensor(0.9183)
epoch: 196 loss: tensor(0.9174)
epoch: 197 loss: tensor(0.9168)
epoch: 198 loss: tensor(0.9169)
epoch: 199 loss: tensor(0.9156)
epoch: 200 loss: tensor(0.9180)

## Testing our SAE

In [25]:
test_loss=0
s=0. # the number of users who only rated

for id_user in range(nb_users):

    input=Variable(training_set[id_user]).unsqueeze(0) # py torch doesn't accept vector of one Dim it takes two dim for patches
    target = Variable(test_set[id_user]).unsqueeze(0)

    
    if torch.sum(target.data>0) > 0:
       output=sae(input)
       target.require_grad=False # don't compute the gradient with respect to the target
       output[target==0]=0 # the values of the correspinds rating in target is equal to 0 (unrated) so we will make it to 0 so that it's not our computation
       loss=criterion(output,target)
       mean_corrector=nb_movies/float(torch.sum(target.data>0)+1e-10)
       test_loss+=np.sqrt(loss.data*mean_corrector)
       s+=1

print('test_loss: '+str(test_loss/s))

test_loss: tensor(0.9519)